import { IItem } from "@/lib/interface/i_item";

// Available items
export const dummyItem: IItem[] = [
  {
    "id": "d3b3f7a4-5c12-4e41-9c0f-3d90db51f49a",
    "name": "Toyota Avanza",
    "merk": "Toyota",
    "category": "Transportasi",
    "color": "Abu-abu",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Jend. Sudirman No. 123",
    "image": "AssetImagePath.dummy_image",
    "description": "Mobil ini digunakan untuk keperluan transportasi sehari-hari."

  },
  {
    "id": "8ea190e0-9144-47b0-a45c-62e539b76c71",
    "name": "Honda Beat",
    "merk": "Honda",
    "category": "Transportasi",
    "color": "Hitam",
    "condition": "Cukup",
    "status": "tidak tersedia",
    "location": "Jalan MH Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Motor ini digunakan untuk kebutuhan transportasi ringan."
  },
  {
    "id": "37b9e7ec-d5b7-4979-a582-625e3e4c94b2",
    "name": "Suzuki Ertiga",
    "merk": "Suzuki",
    "category": "Transportasi",
    "color": "Putih",
    "condition": "Baru",
    "status": "tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "MPV ini cocok untuk keluarga dengan kapasitas penumpang yang luas."
  },
  {
    "id": "2c9fe236-9ff5-4d57-805f-bcf13f80b235",
    "name": "Yamaha NMAX",
    "merk": "Yamaha",
    "category": "Transportasi",
    "color": "Biru",
    "condition": "Rusak Ringan",
    "status": "perawatan",
    "location": "Jalan Merdeka No. 10",
    "image": "AssetImagePath.dummy_image",
    "description": "Motor matic dengan kapasitas mesin besar, sedang dalam perawatan."
  },
  {
    "id": "e4f93cd7-6790-49ec-a64c-1507f1220672",
    "name": "Daihatsu Terios",
    "merk": "Daihatsu",
    "category": "Transportasi",
    "color": "Silver",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "SUV kompak yang sangat cocok untuk perjalanan jarak jauh."
  },
  {
    "id": "d01c6f0f-c163-40bc-9f87-f90065c197e2",
    "name": "Kursi Kantor",
    "merk": "IKEA",
    "category": "Ruangan",
    "color": "Hitam",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Diponegoro No. 34",
    "image": "AssetImagePath.dummy_image",
    "description": "Kursi kantor ergonomis dengan desain yang nyaman untuk bekerja."
  },
  {
    "id": "0e53c563-56e0-44cc-bcc1-02ca43f602b5",
    "name": "Meja Rapat",
    "merk": "Olympic",
    "category": "Ruangan",
    "color": "Coklat",
    "condition": "Cukup",
    "status": "perawatan",
    "location": "Jalan MH Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Meja rapat besar untuk ruang meeting, membutuhkan sedikit perbaikan."
  },
  {
    "id": "d3c1b7fc-45b3-45b2-8f5e-b62c5c004ac5",
    "name": "Lemari Arsip",
    "merk": "Brother",
    "category": "Ruangan",
    "color": "Putih",
    "condition": "Rusak Ringan",
    "status": "tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "Lemari arsip untuk penyimpanan dokumen, dalam kondisi rusak ringan."
  },
  {
    "id": "68776d56-464f-4132-bd0b-9efb2ad625fc",
    "name": "Papan Tulis",
    "merk": "Faber-Castell",
    "category": "Ruangan",
    "color": "Putih",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Merdeka No. 10",
    "image": "AssetImagePath.dummy_image",
    "description": "Papan tulis untuk presentasi dan diskusi di ruang meeting."
  },
  {
    "id": "0f8ecb94-1d4f-44b0-9860-1c62d7d0c4e6",
    "name": "AC Standing",
    "merk": "Daikin",
    "category": "Ruangan",
    "color": "Putih",
    "condition": "Baru",
    "status": "tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "AC berdiri untuk pendinginan ruangan yang cepat dan efisien."
  },
  {
    "id": "5e5f6b5f-555b-4091-a2fa-91beedc8501d",
    "name": "Proyektor Epson",
    "merk": "Epson",
    "category": "Peralatan elektronik",
    "color": "Putih",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Diponegoro No. 34",
    "image": "AssetImagePath.dummy_image",
    "description": "Proyektor untuk presentasi di ruang konferensi."
  },
  {
    "id": "9f81c7f3-beb5-4ed0-a35d-b5b59510f00e",
    "name": "Laptop Dell",
    "merk": "Dell",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Cukup",
    "status": "perawatan",
    "location": "Jalan Jend. Sudirman No. 123",
    "image": "AssetImagePath.dummy_image",
    "description": "Laptop untuk pekerjaan harian, sedang dalam proses perbaikan."
  },
  {
    "id": "71a2bce1-2300-431b-98f3-92d11d768f74",
    "name": "Speaker Bluetooth",
    "merk": "JBL",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Baru",
    "status": "tersedia",
    "location": "Jalan MH Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Speaker Bluetooth dengan suara jernih untuk keperluan audio."
  },
  {
    "id": "6c6b7981-1c1e-4f0b-9279-7d32063de3b4",
    "name": "Smart TV Samsung",
    "merk": "Samsung",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "TV pintar dengan berbagai fitur streaming dan konektivitas."
  },
  {
    "id": "56f64b87-7fa3-4a4e-a216-f5f9a84f96f0",
    "name": "Printer Canon",
    "merk": "Canon",
    "category": "Peralatan elektronik",
    "color": "Putih",
    "condition": "Rusak Ringan",
    "status": "tidak tersedia",
    "location": "Jalan Merdeka No. 10",
    "image": "AssetImagePath.dummy_image",
    "description": "Printer yang sudah tidak berfungsi dengan baik, sedang dalam perbaikan."
  },
  {
    "id": "ad15d03b-d5a7-42cf-9e94-e8ac4fa3cc97",
    "name": "Scanner",
    "merk": "Canon",
    "category": "Peralatan kantor",
    "color": "Abu-abu",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Scanner untuk pemindaian dokumen dengan kualitas tinggi."
  },
  {
    "id": "f3d06eb3-cf72-4ab7-9d4f-4c8f812784ba",
    "name": "Stapler",
    "merk": "Joyko",
    "category": "Peralatan kantor",
    "color": "Hitam",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Diponegoro No. 34",
    "image": "AssetImagePath.dummy_image",
    "description": "Stapler manual untuk keperluan pengikatan dokumen."
  },
  {
    "id": "a2e943e2-f6cc-4235-9de2-d4dbf3b4f242",
    "name": "Mesin Fotocopy",
    "merk": "Fuji Xerox",
    "category": "Peralatan kantor",
    "color": "Putih",
    "condition": "Cukup",
    "status": "perawatan",
    "location": "Jalan Jend. Sudirman No. 123",
    "image": "AssetImagePath.dummy_image",
    "description": "Mesin fotocopy dengan kapasitas tinggi, sedang dalam perawatan."
  },
  {
    "id": "9b071c5b-8a96-4d4e-9d18-24b7ff34f39b",
    "name": "Mic Wireless",
    "merk": "Shure",
    "category": "Peralatan event",
    "color": "Abu-abu",
    "condition": "Hilang",
    "status": "tidak tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk keperluan operasional."
  },
  {
    "id": "f68cc7c3-4d6b-4f5e-9a5d-59b998cc1b42",
    "name": "Router Wifi",
    "merk": "D-Link",
    "category": "Peralatan elektronik",
    "color": "Coklat",
    "condition": "Cukup",
    "status": "perawatan",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk keperluan operasional."
  },
  {
    "id": "08e2decb-021b-45eb-8e11-bcf4f8590ad6",
    "name": "Genset Portable",
    "merk": "Yamaha",
    "category": "Peralatan event",
    "color": "Hitam",
    "condition": "Baru",
    "status": "tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk keperluan operasional."
  },
  {
    "id": "f755cfe0-4104-42a0-b1c1-6fd5c0c0e446",
    "name": "Whiteboard",
    "merk": "Quartet",
    "category": "Peralatan kantor",
    "color": "Putih",
    "condition": "Cukup",
    "status": "perawatan",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk keperluan operasional."
  },
  {
    "id": "157df76a-3467-4c9a-b8df-205738be2f4a",
    "name": "TV LED",
    "merk": "Panasonic",
    "category": "Peralatan elektronik",
    "color": "Abu-abu",
    "condition": "Baik",
    "status": "tidak tersedia",
    "location": "Jalan Diponegoro No. 34",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk keperluan operasional."
  },
  {
    "id": "c788a6b7-269e-4c1f-b1fc-4ffcc180b1cb",
    "name": "Drone Kamera",
    "merk": "DJI",
    "category": "Peralatan event",
    "color": "Putih",
    "condition": "Cukup",
    "status": "tersedia",
    "location": "Jalan Jend. Sudirman No. 123",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk keperluan operasional."
  },
  {
    "id": "6266df1b-c8b3-4f99-9229-d9ad053ea1d2",
    "name": "Lemari Arsip",
    "merk": "Olympic",
    "category": "Ruangan",
    "color": "Coklat",
    "condition": "Cukup",
    "status": "tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "Barang ini digunakan untuk menyimpan dokumen penting."
  },
  {
    "id": "5e2ff81e-4e9b-4c2a-bf38-11c5d6b20db8",
    "name": "Meja Lipat",
    "merk": "Informa",
    "category": "Ruangan",
    "color": "Coklat",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Digunakan untuk acara sementara."
  },
  {
    "id": "6d0cc56b-51ef-4fc7-85f3-e7cf8a5b816f",
    "name": "Headset",
    "merk": "Logitech",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Rusak Ringan",
    "status": "perawatan",
    "location": "Jalan Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Dipakai untuk meeting daring."
  },
  {
    "id": "95e05890-e8f7-44f8-a43b-23c98a7f3e0e",
    "name": "Alat Pemadam Api",
    "merk": "FireFix",
    "category": "Peralatan lainnya",
    "color": "Merah",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Untuk keselamatan darurat."
  },
  {
    "id": "b8cf5619-d3e1-4e52-a7b0-e776531f05ab",
    "name": "Laptop ProBook",
    "merk": "HP",
    "category": "Peralatan elektronik",
    "color": "Silver",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Jend. Sudirman No. 123",
    "image": "AssetImagePath.dummy_image",
    "description": "Digunakan untuk kebutuhan kerja harian."
  },
  {
    "id": "e3fba5df-c160-4d29-bc46-62b5798f9b91",
    "name": "Monitor LED 24 inch",
    "merk": "Dell",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Cukup",
    "status": "perawatan",
    "location": "Jalan Diponegoro No. 34",
    "image": "AssetImagePath.dummy_image",
    "description": "Layar tambahan untuk workstation."
  },
  {
    "id": "ca2b03b4-257c-4601-b97e-c59de7d8786b",
    "name": "Printer Ink Tank",
    "merk": "Epson",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Rusak Ringan",
    "status": "tidak tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "Digunakan untuk mencetak dokumen internal."
  },
  {
    "id": "2ff7f1c7-0f55-4f79-9392-8ec3c6e7d4d7",
    "name": "Speaker Bluetooth",
    "merk": "JBL",
    "category": "Peralatan elektronik",
    "color": "Merah",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Untuk presentasi dan pemutaran musik."
  },
  {
    "id": "c1c848ed-f9df-4df0-805b-b1ee7e52c65a",
    "name": "Smart TV 50 inch",
    "merk": "Samsung",
    "category": "Peralatan elektronik",
    "color": "Hitam",
    "condition": "Baru",
    "status": "tersedia",
    "location": "Jalan Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Digunakan untuk ruang rapat."
  },
  {
    "id": "8b7f88fd-4aa6-42df-8ea3-88550f021872",
    "name": "Scanner Dokumen",
    "merk": "Canon",
    "category": "Peralatan elektronik",
    "color": "Putih",
    "condition": "Cukup",
    "status": "tidak tersedia",
    "location": "Jalan Jend. Sudirman No. 123",
    "image": "AssetImagePath.dummy_image",
    "description": "Untuk mendigitalisasi arsip fisik."
  },
  {
    "id": "bc94825c-7cd4-4fcf-98ab-21c647fb0b41",
    "name": "Projector Mini",
    "merk": "BenQ",
    "category": "Peralatan elektronik",
    "color": "Putih",
    "condition": "Baik",
    "status": "perawatan",
    "location": "Jalan Diponegoro No. 34",
    "image": "AssetImagePath.dummy_image",
    "description": "Digunakan saat presentasi internal."
  },
  {
    "id": "671c4d3f-3c71-4d87-96dc-16ea8c5fc30e",
    "name": "Tablet Android",
    "merk": "Lenovo",
    "category": "Peralatan elektronik",
    "color": "Abu-abu",
    "condition": "Rusak Berat",
    "status": "tidak tersedia",
    "location": "Jalan Gatot Subroto No. 88",
    "image": "AssetImagePath.dummy_image",
    "description": "Sudah tidak berfungsi dan menunggu penggantian."
  },
  {
    "id": "79fc1f2f-d7f0-4087-90ec-13f60a3cbfa5",
    "name": "Keyboard Wireless",
    "merk": "Logitech",
    "category": "Peralatan elektronik",
    "color": "Putih",
    "condition": "Baik",
    "status": "tersedia",
    "location": "Jalan Ahmad Yani No. 56",
    "image": "AssetImagePath.dummy_image",
    "description": "Aksesoris untuk komputer kerja."
  },
  {
    "id": "6a6b3a36-ef0a-4a89-bf8a-96d84647cb64",
    "name": "CCTV Indoor",
    "merk": "Hikvision",
    "category": "Peralatan elektronik",
    "color": "Putih",
    "condition": "Cukup",
    "status": "tersedia",
    "location": "Jalan Thamrin No. 45",
    "image": "AssetImagePath.dummy_image",
    "description": "Untuk pengawasan keamanan kantor."
  }
]
